#!/usr/bin/env bash

node --version
pushd /autograder/submission
pyret submission.arr
popd

pwd
pushd pyret-grading-example
pwd
npm install
node puppet.js -p submission.arr -t tests.arr
cp results.json ..

